branches:
    only:
        - master

sudo: required

language: python

services:
    - docker

script:
    - docker build -t tylerbiggs/chemmd:$TRAVIS_BUILD_NUMBER .
    - docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_PASSWORD"
    - docker push tylerbiggs/chemmd:$TRAVIS_BUILD_NUMBER
