branches:
    only:
        - master

sudo: required

language: python

services:
    - docker

script:
    - docker build -t tylerbiggs/chemmd:$TRAVIS_BUILD_NUMBER .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push tylerbiggs/chemmd:$TRAVIS_BUILD_NUMBER
