branches:
    only:
        - master

sudo: required

language: python

services:
    - docker

script:
    - docker build -t chemmd:$TRAVIS_BUILD_NUMBER .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push chemmd:$TRAVIS_BUILD_NUMBER
